CONFIG_PLANTILLA = {
    "version": "1.0",
    "fila_inicio": 2,
    "fila_tabla": 9,
    "columna_inicio": 2,
    "filas_preestablecidas": 20,
    "encabezado": {
        "borde": True,
        "alto": None,
        "color_fondo": None,
        "color_texto": None,
        "negrita": None,
        "fuente": None,
        "tamaño_fuente": None,
    },
    "filas": {
        "borde": True,
        "alto": None,
        "color_fondo_par": None,
        "color_fondo_impar": None,
    },
    "columnas": [
        {
            "id": "numero",
            "titulo": "N°",
            "tipo": "autonumerico",
            "fondo_gris_fijo": False,
            "validacion_stop": False,
            "ancho": None,
            "mensaje_error": None,
        },
        {
            "id": "nombre_estado",
            "titulo": "Nombre del estado",
            "tipo": "texto_libre",
            "fondo_gris_fijo": False,
            "validacion_stop": False,
            "ancho": None,
            "mensaje_error": None,
        },
        {
            "id": "tipo_carga",
            "titulo": "Tipo de carga",
            "tipo": "lista_desplegable",
            "fuente": "yaml_load_types",
            "fondo_gris_fijo": False,
            "validacion_stop": True,
            "ancho": None,
            "mensaje_error": "El tipo de carga debe pertenecer al reglamento activo.",
        },
        {
            "id": "tipo_estado",
            "titulo": "Tipo de estado",
            "tipo": "lista_desplegable",
            "opciones": ["Simple", "Direccional"],
            "fondo_gris_fijo": False,
            "validacion_stop": True,
            "ancho": None,
            "mensaje_error": "El tipo de estado debe ser Simple o Direccional.",
        },
        {
            "id": "numero_grupo",
            "titulo": "Número de grupo",
            "tipo": "entero_positivo",
            "fondo_gris_fijo": True,
            "validacion_stop": False,
            "ancho": None,
            "mensaje_error": None,
        },
        {
            "id": "incluir_opuesto",
            "titulo": "Incluir opuesto",
            "tipo": "lista_desplegable",
            "opciones": ["Sí", "No"],
            "fondo_gris_fijo": True,
            "validacion_stop": True,
            "ancho": None,
            "mensaje_error": "El valor debe ser Sí o No.",
        },
    ],
    "imagen_empresa": None,
    "panel_referencia": {
        "columnas_separador": 1,
        "titulo_permanentes": "Cargas permanentes declaradas:",
        "titulo_tipos_de_carga": "Tipos de cargas declarados:",
    },
}

CONFIG_RESUMEN = {
    "fila_inicio": 2,
    "columna_inicio": 2,
    "nombre_hoja": "Resumen COMBOS",
    "encabezado_programa": {
        "nombre": "COMBOS",
        "version_combos": "1.0",
        "mostrar_reglamento": True,
        "mostrar_fecha": True,
        "logo": None,
    },
    "estilos": {
        "encabezado_seccion": {
            "color_fondo": None,
            "color_texto": None,
            "negrita": None,
            "fuente": None,
            "tamaño_fuente": None,
            "borde": None,
        },
        "columnas_tabla": {
            "ancho_auto": True,
            "anchos": None,
        },
        "filas": {
            "color_fondo_par": None,
            "color_fondo_impar": None,
            "borde": None,
        },
    },
    "secciones": [
        {
            "id": "datos_ingresados",
            "titulo": "DATOS DE ENTRADA",
            "visible": True,
            "columnas": [
                "Id",
                "Nombre del estado",
                "Tipo de carga",
                "Tipo de estado",
                "Nombre de grupo",
                "Opuesto",
            ],
        },
        {
            "id": "combinaciones_resultantes",
            "titulo": "COMBINACIONES RESULTANTES",
            "visible": True,
            "columnas": [
                "Id",
                "Componentes",
                "Estado límite",
                "Combinación base",
                "Nombre asignado",
            ],
            "criterio": "no_duplicadas_y_superadas_mantenidas",
        },
        {
            "id": "duplicados_eliminados",
            "titulo": "ELIMINADAS POR DUPLICADO",
            "visible": True,
            "columnas": [
                "Id",
                "Componentes",
                "Estado límite",
                "Combinación base",
                "Duplicada por",
            ],
        },
        {
            "id": "superadas",
            "titulo": "SUPERADAS POR OTRAS",
            "visible": True,
            "columnas": [
                "Id",
                "Componentes",
                "Estado límite",
                "Combinación base",
                "Superada por",
            ],
            "filtro": "solo_descartadas",
        },
        {
            "id": "combinaciones_generadas",
            "titulo": "RESUMEN GENERAL",
            "visible": True,
            "columnas": [
                "Id",
                "Componentes",
                "Estado límite",
                "Combinación base",
                "Duplicada por",
                "Superada por",
                "Decisión",
            ],
        },
    ],
}
